version: '3'

networks:
    backend:

services:
  nginx:
    container_name: nginx_container_1
    image: cpublic/nginxssl:latest
    links:
      - cpxstats-1:cpxstats-1
    ports:
      - 80:80
      - 443:443
    volumes:
      - /home/cpxadmin/encryption:/opt/ssl
    privileged: true
    depends_on:
      - cpxstats-1
    restart: always
    networks:
      - backend

  cpxstats-1:
    container_name: netstats_container_1
    image: cpublic/cpxstats:latest
    ports:
      - 3000:3000
    privileged: true
    environment:
      - WS_SECRET=cpx-mainnet
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "10"
    restart: always
    networks:
      - backend